### ISSUE TITLE
statically linked bun

### ISSUE THREAD

**Issue by theoparis** [bun-os/bun-os#3]
The problem with the previous build system is that I had to bundle arch linux libraries into BunOS in order to run bun by itself. I thought the solution would be simple... but as it turns out its much harder than i thought. 

I got bun to be statically linked to glibc, but NAPI and FFI seem to be causing major issues.

![image](https://user-images.githubusercontent.com/11761863/182526257-26fe577a-1819-4d5d-b2fb-43ab81ca7f99.png)

![image](https://user-images.githubusercontent.com/11761863/182526389-931298c5-ba46-4099-be4d-f3b230e64124.png)

**Comment by theoparis** [comment]
Unfortuntely, work on BunOS has been paused due to bun not being a good enough javscript runtime to use. Using JavaScriptCore APIs directly would be a much better idea, but I have no idea as to where to start.

**Comment by tomByrer** [comment]
> Using JavaScriptCore APIs directly would be a much better idea, but I have no idea as to where to start.

He just read JavaScriptCore source code for a month & taught himself:

> the more complicated parts were just like figuring out what all the functions are, what all the corresponding functions are in JavaScript core JavaScript core is not really designed to be easy to be embedded. Like they don't have like the docs they have are for the C API, which is fairly limited in what you can do.
> The C API is mostly designed for iOS apps, embedding javascript core for like a very small thing, like a, like an in game, like something that has some code that for like, like if you have like ads or something so, so bun has to use a lot of the C plus plus private API in JavaScript court. And that really was, that was like a month of just like me reading a bunch of code and web kit.
> It's a huge code base.

@21 minutes in: https://devtools.fm/episode/37?view=TRANSCRIPT

Are you trying to make an entire OS on Bun?  Or just a CLI type tool?

**Comment by theoparis** [comment]
Now that it has been a few months I've realized that I can just have bun build a libc (eg. glibc) and install it to the sysroot. I think this issue can be closed as ffi is needed for other parts of BunOS in the future and static linking could prevent that from working.
